Repository RedHatInsights/uhc-portal, pull requests merged in 2025-08, with the labels that each got.

#43 OCMUI-3243 unit test set 6
  src/components/clusters/wizards/rosa/CIDRScreen/CIDRScreen.test.jsx
  src/components/clusters/wizards/rosa/ClusterProxyScreen.test.jsx
  src/components/clusters/wizards/rosa/ClusterRolesScreen/ClusterRolesScreen.test.jsx
  src/components/common/SkeletonRows.tsx
  src/queries/ClusterListQueries/archived/clusterListSort.js
  src/queries/ClusterListQueries/archived/helpers/createResponseForFetchCluster.ts
  src/queries/ClusterListQueries/archived/helpers/fetchGlobalClusters.ts
  src/queries/ClusterListQueries/archived/helpers/fetchRegionalClusters.ts
  src/queries/ClusterListQueries/archived/helpers/useFetchClustersHelpers.ts
  src/queries/ClusterListQueries/archived/types/types.ts
  src/queries/ClusterListQueries/archived/useFetchClusters.ts
  src/queries/ClusterListQueries/archived/useFetchRegions.ts
Labels: assisted-by-ai

#58 OCMUI-3697, OCMUI-3674: konflux / migrate unit-tests & code-lint in 'push' PL
  .tekton/uhc-portal-push.yaml
Labels: CI/CD

#54 OCMUI-3603: deprecated modals update
  src/common/modals/ConfirmationDialog.tsx
  src/components/SyncEditor/SyncEditorModal.tsx
  src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/ExternalAuthentication/BreakGlassCredentialDetailsModal.tsx
  src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/ExternalAuthentication/DeleteExternalAuthProviderModal.tsx
  src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/ExternalAuthentication/ExternalAuthProviderModal.tsx
  src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/ExternalAuthentication/RevokeBreakGlassCredentialsModal.tsx
  src/components/clusters/ClusterDetailsMultiRegion/components/ClusterLogs/toolbar/ClusterLogsDownload.tsx
  src/components/clusters/ClusterDetailsMultiRegion/components/Networking/components/EditApplicationIngressDialog/EditApplicationIngressDialog.tsx
  src/components/clusters/ClusterDetailsMultiRegion/components/Overview/BillingAccount/OverviewBillingAccountModal.tsx
  src/components/clusters/ClusterDetailsMultiRegion/components/UpgradeSettings/UpgradeSettingsTab.tsx
  src/components/clusters/ClusterTransfer/AcceptDeclineTransferModal.tsx
  src/components/clusters/ClusterTransfer/CancelClusterTransferModal.tsx
  src/components/clusters/common/InstallProgress/ActionRequiredModal.jsx
  src/components/clusters/common/MachineConfiguration/components/MachineConfigurationModal.tsx
  src/components/clusters/common/Upgrades/UpgradeAcknowledge/UpgradeAcknowledgeModal/UpgradeAcknowledgeModal.tsx
Labels: assisted-by-ai

#64 OCMUI-3614: added spacing between alerts
  src/components/clusters/ClusterDetailsMultiRegion/components/ClusterDetailsTop/components/ClusterStatusMonitor/ClusterStatusMonitor.jsx
Labels: bugfix

#66 OCMUI-3696: switch on test-coverage for konflux' "pull-request" PL
  .tekton/uhc-portal-pull-request.yaml
Labels: CI/CD

#49 OCMUI-3618 - When creating a new htpasswd IDP the confirm password field is misaligned
  src/components/common/FormikFormComponents/FormikFieldArray/CompoundFieldArray.jsx
  src/components/common/FormikFormComponents/FormikFieldArray/CompoundFieldArray.scss
Labels: assisted-by-ai

#79 OCMUI-3717: add NPM to renovate package managers
  .github/renovate.json
Labels: CI/CD
